server:
  host: "0.0.0.0"
  port: 8080
  graceful_shutdown_timeout: 30s

logging:
  level: "info"
  format: "json"

metrics:
  enabled: true
  path: "/metrics"

tracing:
  enabled: true
  endpoint: "http://localhost:4318"
  service_name: "signaling-server"

health:
  path: "/health"
  live_path: "/health/live"
  ready_path: "/health/ready" 