[package]
name = "transmitter"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13.5"
actix-web = "4.10.2"
actix-web-actors = "4.3.1"
env_logger = "0.11.7"
log = "0.4.26"
once_cell = "1.21.1"
serde_json = "1.0.140"
serde_urlencoded = "0.7.1"
