[package]
name = "starter"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
gstreamer = "0.23.5"
gstreamer-app = "0.23.5"
gstreamer-video = "0.23.5"
tokio = "1.44.1"
webrtc = "0.12.0"
