version: '3.8'

services:
  signaling-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - LOGGING_LEVEL=debug
      - METRICS_ENABLED=true
      - METRICS_PATH=/metrics
      - TRACING_ENABLED=true
      - TRACING_EXPORTER=otlp
      - TRACING_ENDPOINT=jaeger:4317
      - TRACING_SERVICE_NAME=signaling-server
    depends_on:
      - prometheus
      - jaeger
    restart: unless-stopped
    networks:
      - signaling-network

  prometheus:
    image: prom/prometheus:v2.42.0
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - signaling-network

  jaeger:
    image: jaegertracing/all-in-one:1.41
    ports:
      - "16686:16686" # UI
      - "4317:4317"   # OTLP gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - signaling-network

networks:
  signaling-network:
    driver: bridge