global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'signaling-server'
    scrape_interval: 5s
    static_configs:
      - targets: ['signaling-server:8080']
    metrics_path: /metrics